# Generated by Django 2.2.5 on 2019-12-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ratings',
            field=models.IntegerField(default=2),
        ),
    ]
