# Generated by Django 2.2.5 on 2019-12-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
