# Generated by Django 2.2.5 on 2019-12-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_auto_20191228_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
